### ISSUE TITLE
import problem

### ISSUE THREAD

**Issue by Gaurav192002** [kelvins/steganography#16]
where i can import image path...

**Comment by kelvins** [comment]
Import what? 🤔

**Comment by Gaurav192002** [comment]
image

**Comment by kelvins** [comment]
You can find test images inside the `res` (resources) folder. You can use relative or absolute path to load it. About project imports, it only depends on the `Pillow` package. You can install dependencies using the `requirements` file. More information can be found in the [README](https://github.com/kelvins/steganography/blob/main/README.md) file.
