### ISSUE TITLE
unmerged image not in expected size

### ISSUE THREAD

**Issue by KarthikKailash04** [kelvins/steganography#18]
merge was done as expected but when unmerging the secret image not in its original size.
![Screenshot (13)](https://user-images.githubusercontent.com/128879871/227696113-dff7ceb4-70fd-4d40-81f4-8fb20748b35f.png)

**Comment by kelvins** [comment]
When unmerging the image, we don't know in advance the size of the "hidden" image, this is why we have this black border.
