### ISSUE TITLE
why not working?

### ISSUE THREAD

**Issue by jmfeng01** [kelvins/steganography#4]
python3.81
installed Click and pillow

try to unmerge produce the right image as in readme file, with the given img1.jpg and img2.jpg

![img4](https://user-images.githubusercontent.com/58899121/72011952-7fa3b980-3220-11ea-807c-d4621bf8bd72.jpg)

**Comment by kelvins** [comment]
It is probably related to the issue https://github.com/kelvins/steganography/issues/2. Try to use `png` instead.

**Comment by clsung** [comment]
jpeg is lossy form in this case.

**Comment by kelvins** [comment]
Duplicated https://github.com/kelvins/steganography/issues/2
